name: taxizer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  shared_preferences: ^2.1.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.3
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.11
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  animated_bottom_navigation_bar: ^1.2.0
  permission_handler: ^8.0.0+2
  googleapis: ^11.2.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.2.2
  anim_search_bar: ^2.0.3
  http: ^0.13.6
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.5
  firebase_core: ^2.13.1







dev_dependencies:


  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icons.svg"
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - images/







